### ISSUE TITLE
Maximum call stack exceeded

### ISSUE THREAD

**Issue by karimcambridge** [md678685/justcord-3#6]
RangeError: Maximum call stack size exceeded
    at deepClone (D:\Videos\JC3MP\JC3MP-TM\packages\justcord-3\util.js:32:19)
    at deepMerge (D:\Videos\JC3MP\JC3MP-TM\packages\justcord-3\util.js:45:20)
    at deepMerge (D:\Videos\JC3MP\JC3MP-TM\packages\justcord-3\util.js:62:12)
    at deepMerge (D:\Videos\JC3MP\JC3MP-TM\packages\justcord-3\util.js:62:12)
    at deepMerge (D:\Videos\JC3MP\JC3MP-TM\packages\justcord-3\util.js:62:12)
    at deepMerge (D:\Videos\JC3MP\JC3MP-TM\packages\justcord-3\util.js:62:12)
    at deepMerge (D:\Videos\JC3MP\JC3MP-TM\packages\justcord-3\util.js:62:12)
    at deepMerge (D:\Videos\JC3MP\JC3MP-TM\packages\justcord-3\util.js:62:12)
    at deepMerge (D:\Videos\JC3MP\JC3MP-TM\packages\justcord-3\util.js:62:12)
    at deepMerge (D:\Videos\JC3MP\JC3MP-TM\packages\justcord-3\util.js:62:12)
Package 'justcord' loaded.

---

Whenever I start the server and that happens, package.json gets updated and it loses some information.. this is a github changelog below;

```
@@ -1,29 +1,29 @@
{
  "name": "justcord",
  "version": "0.1.0",
  "description": "A JC3MP-Discord bridge",
  "main": "main.js",
  "repository": {
    "url": "https://github.com/md678685/justcord-3.git",
    "type": "git"
  },
  "author": "md678685 <mathew678@hotmail.co.uk>",
  "license": "MIT",
  "dependencies": {
    "eris": "^0.5.1"
  },
  "devDependencies": {
    "eslint": "3.13.0",
    "eslint-config-airbnb": "^14.0.0",
    "eslint-plugin-import": "2.2.0",
    "eslint-plugin-jsx-a11y": "3.0.2",
    "eslint-plugin-react": "6.9.0"
  },
  "jcmp_dependencies": [
    "chat"
  ],
  "scripts": {
    "test": "echo 'Not yet implemented, use script \"run_server\" to start emulator' && exit 1",
    "run_server": "cp ./*.js jcmpserver/packages/justcord && cd jcmpserver && jcmp-server && rm packages/justcord/*.js"
  }
}
    "author": "md678685 <mathew678@hotmail.co.uk>",
    "dependencies": {
        "eris": "^0.5.1"
    },
    "description": "A JC3MP-Discord bridge",
    "devDependencies": {
        "eslint": "3.13.0",
        "eslint-config-airbnb": "^14.0.0",
        "eslint-plugin-import": "2.2.0",
        "eslint-plugin-jsx-a11y": "3.0.2",
        "eslint-plugin-react": "6.9.0"
    },
    "jcmp_dependencies": [
        "chat"
    ],
    "license": "MIT",
    "main": "main.js",
    "name": "justcord",
    "repository": {
        "type": "git",
        "url": "https://github.com/md678685/justcord-3.git"
    },
    "scripts": {
        "run_server": "cp ./*.js jcmpserver/packages/justcord && cd jcmpserver && jcmp-server && rm packages/justcord/*.js",
        "test": "echo 'Not yet implemented, use script \"run_server\" to start emulator' && exit 1"
    },
    "version": "0.1.0"
}
\ No newline at end of file
```

weird?

**Comment by mdcfe** [comment]
I'm not sure why the `package.json` gets changed, but that seems to happen regardless of the error. I'll revert the config changes for now.

**Comment by mdcfe** [comment]
Justcord 0.2.0 now uses `_.merge` from lodash, rather than the borked util function.
